- README.md
Updates Readme to include correct package path
> update readme and add contributing

- README.md
README: Make provided example consistent with the rest of the documentation.
Resolves #49 
Resolves OKTA-221065
> Update Readme baseurl setting

- README.md
> Update link for landing page

- README.md
> Rdegges restructure readme

- README.md
Expands getting started readme to include some more details.
Resolves #158
> Updates readme getting started

- okta/config.go
> Ymylei time type correction

- README.md
Adds info about retry strategy
> Add information about our retry strategy

- CHANGELOG.md
- okta/okta.go
- openapi/generator/templates/okta.go.hbs
Updates Changelog.md file
Updates version in okta.go and template to 2.1.0
> Update tags for 2.1 release

- go.mod
- go.sum
- okta/error.go
- okta/requestExecutor.go
> OKTA-331913 fix error handling for 401 error

- okta/requestExecutor.go
> Retry on EOF errors from HTTP client

- okta/requestExecutor.go
> Fixed req body error

- CHANGELOG.md
- okta/okta.go
- openapi/generator/templates/okta.go.hbs
Update version and changelog for 2.3.0
> Update version to 2.3.0

- okta/requestExecutor.go
> Add exported OKTA_ACCESS_TOKEN constant

- CONTRIBUTING.md
- README.md
Bringing in @juanmatias's PR #221 and so additional documentation clean up on my part.
> Juanmatias improve oatuh2 servapp doc

- okta/config.go
- okta/requestExecutor.go
- okta/validator.go
Bringing PR https://github.com/okta/okta-sdk-golang/pull/225 from the community.
> Aborrello feature support opaque private keys

- CHANGELOG.md
- openapi/generator/templates/okta.go.hbs
This PR updates the version number from `2.3.0` to `2.3.1`.
> Feature update version

- README.md
Fixing README per feedback from https://github.com/okta/okta-sdk-golang/issues/231
> Correct CreateUser example in README. Fixes issue #231

- okta/requestExecutor.go
@bogdanprodan-okta let me know if this is the correct way to make use of the oktaBackoff class. This is for issue #194
> Utilize oktaBackoff on token requests.

- okta/requestExecutor.go
> Pass previous query parameters to the NextPage URL

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yaml
- .github/SECURITY.md
- .github/pull_request_template.md
Adds Issue Template:
- Bug Report
- Feature Request
Turns off blank issue reporting (must use one of the templates)
Includes a link to the dev forum
Resolves: OKTA-448510
> Add Issue Templates

- README.md
- tests/integration/user_type_test.go
Updated all sample code in the Readme with latest version of the SDK (v2.9.2)
Fixes #275 
Go Version:
Os Version:
> Update Readme example code

- README.md
Fixes #
Go Version:
Os Version:
> Update okta image

- tests/integration/main_test.go
> Index flaw in testPassword

- README.md
- okta/application.go
- okta/brand.go
- okta/group.go
- okta/inlineHookPayload.go
- okta/orgSetting.go
- okta/policy.go
- okta/query/query.go
- okta/requestExecutor.go
- okta/userFactor.go
- okta/validator.go
- tests/unit/client_config_test.go
Helper PR for @outofjungle's external PR #307
- Added Bearer as an authorization mode in addition to SWSS and PrivateKey
> Enabling "Bearer" as an additional AuthorizationMode

- .generator/config.yaml
- .generator/templates/api_application_test.go
- .generator/templates/configuration_test.go
- .generator/templates/model_simple.mustache
- .generator/templates/test_helpers.go
- .generator/templates/user_test.go
- .travis.yml
- okta-management-APIs-oasv3.yaml
To generate the v3 code, please run openapi-generator generate -c ./.generator/config.yaml -i ./management-noEnums-oneOfInheritances.yaml  
Then cd to okta/v3 to run the test
To run a specific test `go test -run ^test_name`
To run all of the test `go test ./...`
Fixes #
N/A
Go Version:
Os Version:
OpenAPI Spec Version: 3.0.3
> Okta 506940 add it for user

- .generator/config.yaml
- .generator/templates/user_schema_test.go
Fixes #
Go Version:
Os Version:
OpenAPI Spec Version: 3.0.3
> Okta 506943 add IT for user schema

- .generator/templates/api.mustache
- .generator/templates/client.mustache
- .generator/templates/response.mustache
- .generator/templates/user_test.go
Fixes #
Go Version:
Os Version:
> add support for pagination

- .generator/config.yaml
- .generator/templates/idp_test.go
- .generator/templates/test_helpers.go
Fixes #
Go Version:
Os Version:
OpenAPI Spec Version: 3.0.3
> Okta 499031 add it for idp

- .generator/config.yaml
- .generator/templates/group_test.go
- .generator/templates/main_test.go
Fixes #
Go Version:
Os Version:
> add IT for group

- .generator/config.yaml
- .generator/templates/api.mustache
- .generator/templates/api_application_test.go
- .generator/templates/client.mustache
- .generator/templates/configuration.mustache
- .generator/templates/go.mod.mustache
- .generator/templates/go.sum
- .generator/templates/private_key_test.go
- .generator/templates/response.mustache
- .generator/templates/retry_logic_test.go
Fixes #
Go Version:
Os Version:
> add support to oauth for okta

- .generator/config.yaml
- .generator/templates/policy_test.go
- .generator/templates/test_helpers.go
- okta-management-APIs-oasv3.yaml
Fixes #
Go Version:
Os Version:
> add policy it

- .generator/config.yaml
- .generator/templates/cache.go
- .generator/templates/cache_test.go
- .generator/templates/client.mustache
- .generator/templates/configuration.mustache
- .generator/templates/go.mod.mustache
- .generator/templates/go.sum
- .generator/templates/gocache.go
- .generator/templates/main_test.go
- .generator/templates/noopcache.go
Fixes #
Go Version:
Os Version:
> add caching

- .generator/templates/api_application_test.go
- .generator/templates/group_test.go
- .generator/templates/idp_test.go
- .generator/templates/main_test.go
- .generator/templates/policy_test.go
- .generator/templates/private_key_test.go
- .generator/templates/test_helpers.go
- .generator/templates/user_schema_test.go
- .generator/templates/user_test.go
- okta-management-APIs-oasv3.yaml
Fixes #
Go Version:
Os Version:
> add support for string enum

- README.md
Bringing over @codersofthedark contribution from #327
> PR 327 codersofthedark

- .github/workflows/prepareReleaseBranch.yml
Fixes #
Go Version:
Os Version:
> update travis to move v3 file to okta folder

- .generator/templates/client.mustache
- .generator/templates/configuration.mustache
- .generator/templates/private_key_test.go
- CHANGELOG.md
- README.md
- okta/config.go
- okta/okta.go
- okta/requestExecutor.go
- okta/validator.go
- openapi/generator/templates/okta.go.hbs
- tests/integration/request_test.go
Fixes #
Go Version:
Os Version:
> add jwt as an authorization mode

- .generator/templates/api_policy_test.go
Fixes #
Go Version:
Os Version:
> add clean up for clone policy

- .generator/templates/configuration.mustache
Fixes #
Go Version:
Os Version:
> add config setter object for v3

- okta/config.go
- tests/unit/client_config_test.go
Bringing in @dnelson27's work.
Closes https://github.com/okta/okta-sdk-golang/pull/371
> @dnelson27's #371

- CHANGELOG.md
Fixes #
Go Version:
Os Version:
> release prep v2.18.0

- go.mod
- go.sum
Fixes #
Go Version:
Os Version:
> upgrade dependency

- CHANGELOG.md
Fixes #
Go Version:
Os Version:
> prep v2.19 release

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update email domain template yaml

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> fix linting

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update spec yaml to correctly generate EmailDomainResponseWithEmbedded

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update default app spec

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update device assurance v3

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update platform type

- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Update spec for domain validation status
Fixes #
Go Version:
Os Version:
> update spec for new domain validation status

- .generator/templates/client.mustache
Fixes #
Go Version:
Os Version:
> update key signer algo

- .generator/config.yaml
- .generator/templates/client.mustache
- .generator/templates/user_agent.go
- okta/requestExecutor.go
Fixes #
Go Version:
Os Version:
Close #408
> add user agent for v2 and v3

- okta/validator.go
I fixed an error message typo
Fixes #
N/A
Error message typo
Go Version: 1.20.3
Os Version: Linux 6.1.26
> Fix typo in error message

- .generator/templates/api_application_test.go
- .generator/templates/api_group_test.go
- .generator/templates/api_idp_test.go
- .generator/templates/api_policy_test.go
- .generator/templates/api_user_schema_test.go
- .generator/templates/api_user_test.go
- .generator/templates/cache_test.go
- .generator/templates/configuration.mustache
- .generator/templates/configuration_test.go
- .generator/templates/main_test.go
- .generator/templates/private_key_test.go
- .generator/templates/proxy_test.go
- .generator/templates/retry_logic_test.go
- .github/workflows/prepareReleaseBranch.yml
Fix orgurl malformed,
Update generator to 7.0.1
Go Version:
Os Version:
Close #404
> fix orgurl malformed

- .generator/config.yaml
- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
Fixes #
Go Version:
Os Version:
> update newest spec

- .generator/config.yaml
- .generator/okta-management-APIs-oasv3-enum-inheritance.yaml
- .generator/templates/api_application_test.go
- .generator/templates/api_idp_test.go
- .generator/templates/api_policy_test.go
Fixes #
Go Version:
Os Version:
> hot fix for terraform

- MIGRATING.md
Fixes #
Go Version:
Os Version:
> add migrating doc to v3

- .generator/templates/user_agent.go
Fixes #
Go Version:
Os Version:
> update user agent

- README.md
Fixes #
Go Version:
Os Version:
> update readme to include migrating guide

- .goreleaser.yaml
Fixes #
Go Version:
Os Version:
> add check sum

- .generator/templates/client.mustache
Fixes #
Go Version:
Os Version:
Close #446
> fix header accept issue that only accept application/json

- .generator/config.yaml
- .generator/templates/client.mustache
- CHANGELOG.md
- openapitools.json
Fixes #
Go Version:
Os Version:
> prep release 4.1.0

- .github/workflows/release.yml
Fixes #
Go Version:
Os Version:
> update gh action

- .generator/templates/client.mustache
- .generator/templates/configuration.mustache
- .generator/templates/private_key_test.go
- .github/workflows/release.yml
Fixes #
Go Version:
Os Version:
> add jwk authentication

- .generator/templates/private_key_test.go
- .generator/templates/response.mustache
Fixes #
Go Version:
Os Version:
Close #468
> fix dpop pagination

- .circleci/config.yml
Update semgrep Circle CI workflow
Closes OKTA-729389
On par with okta-sdk-java
https://github.com/okta/okta-sdk-java/blob/master/.circleci/config.yml#L74-L79
and okta-sdk-dotnet
https://github.com/okta/okta-sdk-dotnet/blob/master/.circleci/config.yml#L66-L73
> Update semgrep Circle CI workflow

- .circleci/config.yml
- .generator/config.yaml
- .github/workflows/prepareReleaseBranch.yml
- CHANGELOG.md
- Makefile
- go.mod
Fixes #
Go Version:
Os Version:
> prep release v5.0.0

- .circleci/config.yml
Fixes #
Go Version:
Os Version:
> Removes cache secrets from CCI config

- .circleci/config.yml
- .generator/okta-management-APIs-oasv3-noEnums-inheritance.yaml
- okta/api/openapi.yaml
- okta/docs/LogActor.md
- okta/docs/LogDebugContext.md
- okta/docs/LogTarget.md
- okta/docs/LogTargetChangeDetails.md
- okta/docs/LogTransaction.md
- okta/docs/Saml11ApplicationSettings.md
- okta/model_log_actor.go
- okta/model_log_debug_context.go
- okta/model_log_target.go
- okta/model_log_target_change_details.go
- okta/model_log_transaction.go
- okta/model_saml11_application_settings.go
Fixes #
Go Version:
Os Version:
Close #482
Close #481
> fix unmarshal error

- CHANGELOG.md
- MIGRATING.md
- README.md
Fixes #
Go Version:
Os Version:
> prep release 5.0.1

- .generator/okta-management-APIs-oasv3-noEnums-inheritance.yaml
- CHANGELOG.md
- okta/api/openapi.yaml
- okta/docs/GroupOwner.md
- okta/model_group_owner.go
Fixes #
Go Version:
Os Version:
> fix group owner

- .circleci/config.yml
- CHANGELOG.md
- okta/main_test.go
Fixes #
Go Version:
Os Version:
> add reversing labs

- .generator/templates/cache_test.go
- .generator/templates/client.mustache
- okta/cache_test.go
- okta/client.go
- okta/main_test.go
Fixes #
Go Version:
Os Version:
Close #458
> update oauth2 method, adding id to client assertion

- .circleci/config.yml
This PR adds the Snyk SCA to the CircleCI config.
Go Version:
Os Version:
> feat: add snyk sca to circleci

- README.md
Fixes https://github.com/okta/okta-sdk-golang/issues/507
> docs: update README for 5.x release

- .github/workflows/prepareReleaseBranch.yml
- .github/workflows/release.yml
> fix: use `go-version-file` in github workflows

- README.md
Clicking the Contributing Guide link in the Contributing section of the README currently results in a 404 - Page Not Found error.
N/A
Go Version:
Os Version:
> Fix broken Contributing Guide link in README
